Remove Intentional Fail

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -563,10 +563,10 @@ jobs:
             export SUCCESS=$(curl --insecure https://kvdb.io/YRSzGWJG8T1Fu6GGmGELCa/migration_${CIRCLE_WORKFLOW_ID:0:7})
             echo SUCCESS=$SUCCESS      
       
-      - run:
-          name: Intentionally fail
-          command: |
-            exit 1
+      # - run:
+      #     name: Intentionally fail
+      #     command: |
+      #       exit 1
 
       - persist_to_workspace:
             root: ./backend
@@ -576,7 +576,7 @@ jobs:
       - create-to-destroy
 
       - revert-migrations
-  
+ 
    
   deploy-frontend:
     docker:
@@ -650,31 +650,31 @@ jobs:
 workflows:
   default:
     jobs:
-      # - setup-cloudfront
-      # - setup-s3-bucket:
-      #     requires: [setup-cloudfront]
-      # - build-frontend:
-      #     context: slack-env
-      # - build-backend:
-      #     context: slack-env
-      # - test-frontend:
-      #     requires: [build-frontend]
-      # - test-backend:
-      #     requires: [build-backend]
-      # - scan-backend:
-      #     requires: [build-backend]
-      # - scan-frontend:
-      #     requires: [build-frontend]
-      # - deploy-infrastructure:
-      #     requires: [test-frontend, test-backend, scan-frontend, scan-backend]
-      #     #filters:
-      #       #branches:
-      #         #only: [test-feature-branch]
-      # - configure-infrastructure:
-      #     requires: [deploy-infrastructure]
-      # - run-migrations:
-      #     requires: [configure-infrastructure]
-      # - deploy-frontend:
-      #     requires: [run-migrations, s3-bucket]
-      - run-migrations
+      - setup-cloudfront
+      - setup-s3-bucket:
+          requires: [setup-cloudfront]
+      - build-frontend:
+          context: slack-env
+      - build-backend:
+          context: slack-env
+      - test-frontend:
+          requires: [build-frontend]
+      - test-backend:
+          requires: [build-backend]
+      - scan-backend:
+          requires: [build-backend]
+      - scan-frontend:
+          requires: [build-frontend]
+      - deploy-infrastructure:
+          requires: [test-frontend, test-backend, scan-frontend, scan-backend]
+          #filters:
+            #branches:
+              #only: [test-feature-branch]
+      - configure-infrastructure:
+          requires: [deploy-infrastructure]
+      - run-migrations:
+          requires: [configure-infrastructure]
+      - deploy-frontend:
+          requires: [run-migrations, s3-bucket]
+      
       
